### ISSUE TITLE
Add a script to shred and remove files

### ISSUE THREAD

**Issue by chronos000** [cfgnunes/nautilus-scripts#14]
The purpose of the script would be to call `shred --iterations=1 --zero --remove`

This could be one way of achieving this:
```
ITERATIONS=1
sed '/^$/d' <<< $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS | xargs -d'\n' shred --iterations=$ITERATIONS --zero --remove 2>&1
```

But `shred` is a very dangerous command, and should not be ran lightly. There should be a warning window before running the script, listing the files about to be shredded and asking for confirmation. Optionally, the same window could have a holder to choose the number of iterations to pass into `shred`. In my example, I hardcoded only one pass, which is generally enough.

**Comment by cfgnunes** [comment]
Hello @chronos000! Thank you for suggesting the feature request!

I find the concept of implementing a "secure delete" functionality through commands like `shred` quite valuable, and plan to work on integrating this script shortly.

However, it's important to recognize certain limitations associated with this approach:

- Its effectiveness might be compromised on file systems that don't overwrite data directly, such as those utilizing journaling, log-structuring, or copy-on-write techniques (for example, ext3/4 in specific modes, XFS, Btrfs, ZFS).
- Secure deletion is particularly challenging on SSDs due to the wear-leveling mechanisms and other SSD-centric technologies, which prevent direct data overwriting.
- In certain file systems, automatic duplication of file segments occurs, which cannot be reliably eradicated using commands like `shred` or `srm`.

**Comment by cfgnunes** [comment]
Hi @chronos000!

The feature you requested is now available in the 'main' branch. You'll find the script under the menu: **Forensic -> Secure delete (shred)**.

For the deletion process, I've configured the script to use the command: `shred --force --zero --remove`. This command will operate with the default setting of 3 iterations, which I believe offers a robust balance between security and efficiency.

To enhance the user experience, I've also introduced a dialog box that lists all files targeted for deletion, allowing for a final review before the process begins (see the attached screenshot).

![Screenshot from 2024-03-13 20-29-43](https://github.com/cfgnunes/nautilus-scripts/assets/5264823/73b734ca-a371-4f14-b8a7-188f8526802e)

Could you please take a moment to test the script and share your feedback?

Thank you for your time and support.
