### ISSUE TITLE
How many files/images is too many for your script to convert, and the argument list too long?

### ISSUE THREAD

**Issue by Username23453** [cfgnunes/nautilus-scripts#18]

**Comment by cfgnunes** [comment]
The problem occurs because the file manager do not pass large argument lists to the scripts. The operating system imposes this limit.

In most Unix-like systems, including Linux, the maximum length of the command-line arguments is determined by the kernel and is controlled by the `ARG_MAX` constant. This limit can vary depending on the system configuration, but it's typically in the range of several megabytes.

The actual number of files or images that would trigger this error depends on various factors:

1. **Length of file paths:** Longer file paths consume more characters in the argument list, potentially reducing the number of files you can pass.
2. **Size of file names:** If the file names are very long, it will limit the number of files you can pass.
3. **Other command-line arguments:** If your command has other arguments apart from the file names, they also contribute to the length of the argument list.

Briefly speaking: there is no an exact number of files/images that is too many.

You can consider the alternative of processing files in batches: Divide the files into smaller batches and process each batch separately.
