### ISSUE TITLE
Add 'Move and leave a symbolic link behind'

### ISSUE THREAD

**Issue by ak-42** [cfgnunes/nautilus-scripts#21]
Hi.

I have (another) script idea. Often when I'm moving large files around to manage storage (for example, moving things to my secondary drive) I find myself copying the files over, having to wait for them to copy over (and potentially waiting a long time if I'm moving hundreds of gigs). When it is done, I need to go back to the original location, delete the original files, and create a symbolic link from the new location to the old location, so that any programs that expect the files in the old location don't freak out.

It'd be helpful if there was a script that performed a move of the files and when the files were done moving, it would leave a symbolic link with the same name as the moved files in the old location.

Thanks for all the effort so far, I really appreciate it.

**Comment by cfgnunes** [comment]
Hello @ak-42 !

Thank you for submitting your feature request.

However, your request appears to be a bit specific and may not cater to the needs of other users.

Furthermore, the functionality you're suggesting involves scripts performing move or copy operations, and the scripts cannot display file transfer progress status similar to what's seen in GNOME Files (progress, percentage, estimated time, etc.).

For these reasons, I think that the implementation of this script will not be good.

If you have any further suggestions or questions, feel free to let me know.

**Comment by ak-42** [comment]
Fair enough. I hadn't thought about the complexity of handling the copying (and then deleting, which can't go wrong) via a script. I think I just miss the functionality of [SteamMover](https://www.traynier.com/software/steammover) I used long ago on Windows. Still, existing scripts cover much of this functionality, with only a few extra steps.

Thanks for your time and efforts.

**Comment by cfgnunes** [comment]
Hi @ak-42,

I was thinking about your feature request today, and one possible alternative came to mind. Instead of having a script handle both the file transfer and link creation, you could move the files normally using the file manager, and then use the already implemented scripts: **“Paste as symbolic link”** or **“Paste as hard link”**.

The advantage of this approach is that the file movement itself would be managed by GNOME Files, which already provides progress status, percentage, and estimated time remaining. After that, the existing scripts can quickly create the links in the original location.
