### ISSUE TITLE
How to manage update(s)?

### ISSUE THREAD

**Issue by HarshalRathore** [cfgnunes/nautilus-scripts#28]
Hi, @cfgnunes 
Hope you are doing great. Currently to install script and shortcut the recommended method is the install.sh script but how do the users keep in touch with the updates? Do we have occasionally pull the git repo to check for updates and re-run the script if this could be converted into a package for example an AUR(Arch User Repository) although this will only resolve it for arch linux, this way the updates can be mainted by the package manager.
Thanks for this awesome project.

**Comment by cfgnunes** [comment]
Hi @HarshalRathore !
Thank you for reaching out and for your kind words about the project!

At the moment, the project does not have a dedicated update process. In this case, you would need to reinstall the script manually to get the latest updates. While it’s possible to automate updates through packaging, maintaining packages for different distros (e.g., Debian, Fedora) adds a significant workload due to the variations in package management systems and requirements.

That said, your suggestion about creating something like an AUR package is a great idea, though it would only solve the problem for Arch-based systems. If you have other ideas or insights on how to streamline this for multiple distributions, I’d love to hear them!

**Comment by HarshalRathore** [comment]
I am a bit familiar with creating AUR packages so I'll try to create one for this project.

**Comment by cfgnunes** [comment]
@HarshalRathore 
Thank you so much for your effort in creating the AUR packages for this project. I really appreciate it! Once they’re ready, I’d be delighted to test them on my Arch Linux.

Thanks again for contributing to making this project even more accessible!
